name: packagecloud
on: [ push ]
jobs:
  build-ubuntu-artifact-12:
    runs-on: ${{ matrix.distrib }}
    strategy:
      matrix:
        distrib:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create artifact
        run: |
          export PG_VERSION=12
          export PG_CONFIG=/usr/lib/postgresql/$PG_VERSION/bin/pg_config
          ./.github/ubuntu-prepare.sh
          make
