name: regression
on:
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    strategy:
      matrix:
        pg_version: [10, 11, 12, 13, 14, 15, 16, 17]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Tests
        run: sudo PGVERSION=${{ matrix.pg_version }} ./scripts/regression.sh
