name: regression
on: [push]
jobs:

  test-10:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Tests
      run: sudo PGVERSION=10 ./scripts/regression.sh

  test-11:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Tests
      run: sudo PGVERSION=11 ./scripts/regression.sh

  test-12:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Tests
      run: sudo PGVERSION=12 ./scripts/regression.sh

  test-13:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Tests
      run: sudo PGVERSION=13 ./scripts/regression.sh

  test-14:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Tests
      run: sudo PGVERSION=14 ./scripts/regression.sh
